CREATE TABLE SALARIES (
    id NUMBER(*,0) PRIMARY KEY,
    employee_id NUMBER(*,0) NOT NULL,
    project_id NUMBER(*,0),
    salary NUMBER(10,2),
    FOREIGN KEY (employee_id) REFERENCES EMPLOYEES(id),
    FOREIGN KEY (project_id) REFERENCES PROJECTS(id)
);

CREATE TABLE EMPLOYEES (
    id NUMBER(*,0) PRIMARY KEY,
    manager_id NUMBER(*,0),
    date_of_joining DATE NOT NULL,
    full_name VARCHAR2(255 BYTE) NOT NULL,
    FOREIGN KEY (manager_id) REFERENCES EMPLOYEES(id)
);

CREATE TABLE PROJECTS (
    id NUMBER(*,0) PRIMARY KEY,
    code VARCHAR2(255 BYTE) NOT NULL,
    manager_id NUMBER(*,0),
    budget NUMBER(10,2) NOT NULL,
    date_of_beginning DATE,
    date_of_ending DATE,
    FOREIGN KEY (manager_id) REFERENCES EMPLOYEES(id)
);

SELECT COUNT(*) FROM EMPLOYEES
INNER JOIN PROJECTS ON PROJECTS.MANAGER_ID = EMPLOYEES.ID
WHERE PROJECTS.CODE = '44905736599';

SELECT FULL_NAME FROM EMPLOYEES 
INNER JOIN SALARIES ON SALARIES.EMPLOYEE_ID = EMPLOYEES.ID
WHERE SALARY >= 1000 AND SALARY <= 2500;





